### ISSUE TITLE
node-speaker does not load in Windows 8

### ISSUE THREAD

**Issue by jhbruhn** [TooTallNate/node-speaker#40] opened 2014-08-16 17:18 UTC
When requiring node-speaker, nothing happens. The program is stuck at the `require('speaker')`.
I'm using Windows 8.1 with Visual Studio 2013 and node 0.10.26

**Comment by WeeJeWel** [comment] 2015-01-02 01:45
+1

**Comment by RTK** [comment] 2015-01-02 23:30
same issue with me

**Comment by diogonfs** [comment] 2015-01-13 19:46
Same issue with me, tested with visual studio 2013, 2012, 2010 and windows 7 32bits and none of this combinations worked.
I also tried to change the mpg123 library, but i don't know how to build properly.

**Comment by tenbits** [comment] 2015-01-20 12:52
Does anybody have a solution to the issue? `bindings` library just freezes requiring `binding.node`. _Have tried newer mpg123, rebuilded gyp with `Release` configuration, nothing have helped._

**Comment by mamartin** [comment] 2015-02-28 16:24
same issue here, getting this:

Error: Symbol binding_module not found.
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at bindings (C:\xampp\htdocs\test\node_modules\speaker\node_modules\bindings\bindings.js:76:44)
    at Object.eval (C:\xampp\htdocs\test\node_modules\speaker\index.js:8:34)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)

Cant it be caused by NODE_MODULE(module_name, Initialize) missing as in [here](https://github.com/brianc/node-postgres/issues/222)?

**Comment by mete89** [comment] 2015-04-21 16:02
Not working when changing win32.c file. windows 8.1

**Comment by RTK** [comment] 2015-04-25 13:01
Props to mete89, it works!

For you lazy folks, I created a folk and replaced the file: https://github.com/RTK/node-speaker

**Comment by Edudjr** [comment] 2015-05-11 21:34
RTK just saved my life :')
How did you do it?

**Comment by jgod** [comment] 2015-05-12 05:12
+1

**Comment by RTK** [comment] 2015-05-12 13:07
@Edudjr as @mete89 mentioned, just replace the win32.c file with an updated version from latest version of mpg123.

@jgod unforunately there is an pull request from @jkeylu since 21st March around (which I didn't notice before I forked the project and fixed the issue), so I do not think it will be fixed in the near future.

**Comment by 1j01** [comment] 2015-08-11 01:45
+1 (Windows 10) Issue title should probably be changed to just "Windows"

**Comment by dfcreative** [comment] 2015-10-04 03:09
Gosh, that worked. Thanks @RTK, you’re saviour.

**Comment by dfcreative** [comment] 2016-01-29 02:20
@RTK @TooTallNate hello guys!
This issue is still acute on windows machines, I guess no one windows user can use `npm/speaker`.
What are the reasons preventing from creating a PR and merging it? The fork is very good.

**Closed** 2016-04-10 01:56 UTC
